-- com.auth definition

CREATE TABLE `auth` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `AUT_NM` varchar(100) DEFAULT NULL COMMENT 'AUT_NM',
  `AUT_NUM` varchar(5) DEFAULT NULL COMMENT 'AUT_NUM',
  `AUT_DESC` text COMMENT 'AUT_DESC',
  `DATA_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'DATA_TYPE_CD',
  `PGM_OBJ_TYPE_CD` varchar(20) DEFAULT NULL COMMENT '프로그램 오브젝트 권한 유형 코드',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH';


-- com.auth_group definition

CREATE TABLE `auth_group` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트ID',
  `AUTH_NUM` varchar(5) DEFAULT NULL COMMENT '권한 그룹 번호',
  `AUTH_GROUP_NAME` varchar(50) DEFAULT NULL COMMENT '권한 그룹 명',
  `AUTH_DATA_GROUP_TYPE` varchar(32) DEFAULT NULL COMMENT 'DATA 권한그룹 유형',
  `UNDER_GRP_BASE_DEPT_NUM` varchar(32) DEFAULT NULL COMMENT 'DATA 하위그룹 기준부서코드',
  `USE_FLAG` char(1) DEFAULT '1' COMMENT 'USE_FLAG',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `AUT_GROUP_STATUS` varchar(32) DEFAULT NULL COMMENT 'AUT_GROUP_STATUS',
  `AUT_GROUP_DESC` text COMMENT 'AUT_GROUP_DESC',
  `AUT_GROUP_NM` varchar(100) DEFAULT NULL COMMENT 'AUT_GROUP_NM',
  `RECORD_YN` char(1) DEFAULT 'N' COMMENT '녹음파일 청취 권한',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='권한그룹';


-- com.auth_group_rel definition

CREATE TABLE `auth_group_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `AUT_GROUP_ID` varchar(32) DEFAULT NULL COMMENT 'AUT_GROUP_ID',
  `AUT_ID` varchar(32) DEFAULT NULL COMMENT 'AUT_ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_GROUP_REL';


-- com.auth_menu_rel definition

CREATE TABLE `auth_menu_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `AUT_ID` varchar(32) DEFAULT NULL COMMENT 'AUT_ID',
  `MENU_ID` varchar(32) DEFAULT NULL COMMENT 'MENU_ID',
  `RETV_BUTT_AUT` tinyint DEFAULT NULL COMMENT 'RETV_BUTT_AUT',
  `CRET_BUTT_AUT` tinyint DEFAULT NULL COMMENT 'CRET_BUTT_AUT',
  `UPDATE_BUTT_AUT` tinyint DEFAULT NULL COMMENT 'UPDATE_BUTT_AUT',
  `DEL_BUTT_AUT` tinyint DEFAULT NULL COMMENT 'DEL_BUTT_AUT',
  `DATA_AUT` varchar(32) DEFAULT NULL COMMENT 'DATA_AUT',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_MENU_REL';


-- com.auth_object_rel definition

CREATE TABLE `auth_object_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `AUT_ID` varchar(32) DEFAULT NULL COMMENT 'AUT_ID',
  `UI_OBJ_ID` varchar(32) DEFAULT NULL COMMENT 'UI_OBJ_ID',
  `UI_VIEW_CD` varchar(32) DEFAULT NULL COMMENT 'UI_VIEW_CD',
  `PGM_ID` varchar(32) DEFAULT NULL COMMENT 'PGM_ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_OBJECT_REL';


-- com.auth_pgm_rel definition

CREATE TABLE `auth_pgm_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `AUTH_ID` varchar(32) NOT NULL COMMENT '권한 RID',
  `PGM_ID` varchar(32) NOT NULL COMMENT '프로그램 RID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_MENU';


-- com.auth_user_rel definition

CREATE TABLE `auth_user_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `EMP_ID` varchar(32) DEFAULT NULL COMMENT 'EMP_ID',
  `RID_USER` varchar(32) DEFAULT NULL COMMENT 'RID_USER',
  `AUT_GROUP_ID` varchar(32) DEFAULT NULL COMMENT 'AUT_GROUP_ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_USER_REL';


-- com.auth_usr definition

CREATE TABLE `auth_usr` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `AUTH_GROUP_ID` varchar(32) NOT NULL COMMENT '권한그룹 아이디',
  `MEM_ID` varchar(32) NOT NULL COMMENT '사용자(직원) 아이디',
  `LANG` char(2) DEFAULT NULL COMMENT 'LANG',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='AUTH_USR';


-- com.com_auth_log definition

CREATE TABLE `com_auth_log` (
  `RID` varchar(32) NOT NULL COMMENT 'PK',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `SRCH_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '조회일시',
  `AUTH_LOG_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '유형 (공통코드:COM_AUTH_LOG_TYPE_CD)',
  `LOG_TYPE_DTL` varchar(32) DEFAULT NULL COMMENT '유형상세 (공통코드:LOG_TYPE_DTL)',
  `WORK_USER_RID` varchar(32) DEFAULT NULL COMMENT '작업자 USER ID',
  `SRC_RID` varchar(32) DEFAULT NULL COMMENT '원천 ID',
  `SRC_NM` varchar(100) DEFAULT NULL COMMENT '원전명',
  `TARGET_RID` varchar(32) DEFAULT NULL COMMENT '목적지 ID',
  `TARGET_NM` varchar(100) DEFAULT NULL COMMENT '목적지 명',
  `OBJ_RID` varchar(32) DEFAULT NULL COMMENT '대상(사용자,권한그룹, 권한) 오브젝트 ID',
  `OBJ_NM` varchar(100) DEFAULT NULL COMMENT '대상 오브젝트명',
  `EVNT_CD` varchar(100) DEFAULT NULL COMMENT '이벤트코드, 700/ 701',
  `EVNT_NM` varchar(100) DEFAULT NULL COMMENT '이벤트명, 계정생성/ 계정삭제',
  `EVNT_SVRY` varchar(100) DEFAULT NULL COMMENT '이벤트심각도,상/ 중/ 하',
  `HOST_NM` varchar(100) DEFAULT NULL COMMENT '작업호스트명,사용자 컴퓨터 HostName',
  `IP` varchar(100) DEFAULT NULL COMMENT '사용자 IP',
  `USER_ID` varchar(50) DEFAULT NULL COMMENT '사용자ID',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='권한 변경로그';


-- com.com_cond_log definition

CREATE TABLE `com_cond_log` (
  `RID` varchar(32) NOT NULL COMMENT 'PK',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `SRCH_DT` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '조회일시',
  `PAGE_RID` varchar(100) DEFAULT NULL COMMENT '페이지 ID',
  `SRCH_USER_RID` varchar(32) DEFAULT NULL COMMENT '조회자 ID',
  `SRCH_COND_RID` varchar(32) DEFAULT NULL COMMENT '조회조건 ID (RID_MBR)',
  `RSLT_CNT` int DEFAULT NULL COMMENT '조회결과 건수',
  `EVNT_CD` varchar(100) DEFAULT NULL COMMENT '이벤트코드',
  `EVNT_NM` varchar(100) DEFAULT NULL COMMENT '이벤트명',
  `EVNT_SVRY` varchar(100) DEFAULT NULL COMMENT '이벤트심각도,상/ 중/ 하',
  `HOST_NM` varchar(100) DEFAULT NULL COMMENT '작업호스트명,사용자 컴퓨터 HostName',
  `IP` varchar(100) DEFAULT NULL COMMENT '사용자 IP',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='개인정보조회이력';


-- com.com_elec_aprv definition

CREATE TABLE `com_elec_aprv` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `ELEC_APRV_NO` varchar(12) DEFAULT NULL COMMENT '전자결재 번호',
  `ELEC_APRV_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '전자결재 유형 코드',
  `ELEC_APRV_DIV_CD` varchar(32) DEFAULT NULL COMMENT '전자결재 구분 코드',
  `CAM_ID` varchar(32) DEFAULT NULL COMMENT '캠페인 아이디',
  `ELEC_APRV_TITLE` varchar(500) DEFAULT NULL COMMENT '전자결재 제목',
  `ELEC_APRV_SBST` text COMMENT '전자결재 내용',
  `ELEC_APRV_STATUS_CD` varchar(32) DEFAULT NULL COMMENT '전자결재 상태 코드',
  `ELEC_APRV_RQTR_ID` varchar(32) DEFAULT NULL COMMENT '전자결재 요청자 아이디',
  `ELEC_APRV_RQTR_ORG_ID` varchar(32) DEFAULT NULL COMMENT '전자결재 요청자 조직 아이디',
  `ELEC_APRV_CMPLT_RQT_DD` datetime DEFAULT NULL COMMENT '전자결재 완료 요청 일자',
  `LAST_APV_DD` datetime DEFAULT NULL COMMENT '최종 승인 일자',
  `LAST_APVR_ID` varchar(32) DEFAULT NULL COMMENT '최종 승인자 아이디',
  `ELEC_APRV_DESC` varchar(200) DEFAULT NULL COMMENT '전자결재 설명',
  `ATRIB_1` varchar(50) DEFAULT NULL COMMENT '속성 1',
  `ATRIB_2` varchar(50) DEFAULT NULL COMMENT '속성 2',
  `ATRIB_3` varchar(50) DEFAULT NULL COMMENT '속성 3',
  `ATRIB_4` varchar(50) DEFAULT NULL COMMENT '속성 4',
  `ATRIB_5` varchar(50) DEFAULT NULL COMMENT '속성 5',
  `ATRIB_6` varchar(50) DEFAULT NULL COMMENT '속성 6',
  `ATRIB_7` varchar(50) DEFAULT NULL COMMENT '속성 7',
  `ATRIB_8` varchar(50) DEFAULT NULL COMMENT '속성 8',
  `ATRIB_9` varchar(50) DEFAULT NULL COMMENT '속성 9',
  `ATRIB_10` varchar(50) DEFAULT NULL COMMENT '속성 10',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='전자결재승인';


-- com.com_elec_aprv_item definition

CREATE TABLE `com_elec_aprv_item` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `ELEC_APRV_ID` varchar(32) NOT NULL COMMENT '전자결재 아이디',
  `ELEC_APRV_SEQ` int DEFAULT NULL COMMENT '전자결재 순번',
  `APVR_ID` varchar(32) DEFAULT NULL COMMENT '승인자 아이디',
  `APVR_ORG_ID` varchar(32) DEFAULT NULL COMMENT '승인자 조직 아이디',
  `APV_DD` datetime DEFAULT NULL COMMENT '승인일자',
  `APVR_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '승인자 유형 코드',
  `ELEC_APRV_STATUS_CD` varchar(32) DEFAULT NULL COMMENT '전자결재 상태 코드',
  `REJECT_DD` datetime DEFAULT NULL COMMENT '반려 일자',
  `REJECT_RSN` varchar(100) DEFAULT NULL COMMENT '반려 사유',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='전자결재 승인자 승인상태';


-- com.com_elec_aprv_mst definition

CREATE TABLE `com_elec_aprv_mst` (
  `RID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `ELEC_APRV_TYPE` varchar(30) DEFAULT NULL COMMENT '전자결재 업무유형',
  `ELEC_APRV_TBL_NM` varchar(50) DEFAULT NULL COMMENT '전자결재 업무테이블',
  `RID_ELEC_REQ_TMPL` varchar(32) DEFAULT NULL COMMENT '전자결재 요청 TEMPLATE',
  `RID_ELEC_APRV_TMPL` varchar(32) DEFAULT NULL COMMENT '전자결재 승인 TEMPLATE',
  `RID_ELEC_RJT_TMPL` varchar(32) DEFAULT NULL COMMENT '전자결재 거절 TEMPLATE',
  `ELEC_REQ_FUNC_NM` varchar(30) DEFAULT NULL COMMENT '전자결재 요청 TEMPLATE',
  `ELEC_APRV_FUNC_NM` varchar(30) DEFAULT NULL COMMENT '전자결재 승인 TEMPLATE',
  `ELEC_RJT_FUNC_NM` varchar(30) DEFAULT NULL COMMENT '전자결재 거절 TEMPLATE',
  `ELEC_REQ_AUTOMAIL_ID` varchar(32) DEFAULT NULL COMMENT '전자결재 요청 TEMPLATE 썬더메일 암호화된자동메일ID',
  `ELEC_APRV_AUTOMAIL_ID` varchar(32) DEFAULT NULL COMMENT '전자결재 승인 TEMPLATE 썬더메일 암호화된자동메일ID',
  `ELEC_RJT_AUTOMAIL_ID` varchar(32) DEFAULT NULL COMMENT '전자결재 거절 TEMPLATE 썬더메일 암호화된자동메일ID',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='전자결재승인마스터';


-- com.com_excel_downl_log definition

CREATE TABLE `com_excel_downl_log` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT '국가코드',
  `LANG` char(2) NOT NULL DEFAULT 'ko' COMMENT '언어코드',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT '화폐단위',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트아이디',
  `REQ_DT` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '요청일시',
  `REQ_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '요청유형코드',
  `REQ_URL` varchar(400) DEFAULT NULL COMMENT '요청URL',
  `REQ_IP` varchar(32) NOT NULL COMMENT '요청IP',
  `REQ_SESSN_ID` varchar(100) NOT NULL COMMENT '요청세션아이디',
  `REQ_LOGIN_ID` varchar(32) NOT NULL COMMENT '요청로그인아이디',
  `TARGET_ID` varchar(32) DEFAULT NULL COMMENT '대상아이디',
  `DOWN_FILE_PATH` varchar(200) DEFAULT NULL COMMENT '서버에 저장되어 있는 파일 경로',
  `COND_WHERE` text COMMENT '조회조건',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='COM_EXCEL_DOWNL_LOG';


-- com.com_extr_col definition

CREATE TABLE `com_extr_col` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT 'ACCNT_ID',
  `EXTR_TBL_ID` varchar(32) NOT NULL COMMENT '외부 테이블 ID',
  `COL_ENG_NM` varchar(50) NOT NULL COMMENT '컬럼영문명',
  `COL_KOR_NM` varchar(50) NOT NULL COMMENT '컬럼한글명',
  `COL_TYPE_CD` varchar(32) NOT NULL COMMENT '컬럼유형코드',
  `COL_SIZE` varchar(11) DEFAULT NULL COMMENT '컬럼사이즈',
  `COL_DESC` varchar(100) DEFAULT NULL COMMENT '컬럼 설명',
  `VAL_MAX_SIZE` int DEFAULT NULL COMMENT '값 최대 길이',
  `FLAG_ATRIB_VAL` varchar(30) DEFAULT NULL COMMENT '데이터 속성 값',
  `WHERE_SCH_MEMID` varchar(30) DEFAULT NULL COMMENT '조회 조건 회원컬럼',
  `WHERE_SCH_HP` varchar(50) DEFAULT NULL COMMENT '조회 조건 전화번호',
  `WHERE_SCH_EMAIL` varchar(50) DEFAULT NULL COMMENT '조회 조건 이메일',
  `COND_CALMT` varchar(300) DEFAULT NULL COMMENT '조건산출식',
  `MKT_COL_MAPPG` varchar(50) DEFAULT NULL COMMENT '마케팅컬럼매핑',
  `COL_ATRIB_DEF_CD_ID` varchar(30) DEFAULT NULL COMMENT '컬럼속성정',
  `ENC_COL_YN` char(1) DEFAULT NULL COMMENT '암호화컬럼여부',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='외부컬럼';


-- com.com_extr_col_chnl_rel definition

CREATE TABLE `com_extr_col_chnl_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT 'ACCNT_ID',
  `EXTR_COL_ID` varchar(32) NOT NULL COMMENT '외부 컬럼 아이디',
  `CHNL_TYPE` varchar(32) NOT NULL COMMENT '채널 아이디',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='외부 컬럼 채널 관계 테이블';


-- com.com_extr_ftp definition

CREATE TABLE `com_extr_ftp` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT '국가코드',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT '화폐단위',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT 'Account ID',
  `FTP_PRPS_CD_ID` varchar(32) DEFAULT NULL COMMENT 'FTP목적코드아이디',
  `FTP_PROT_CD_ID` varchar(32) DEFAULT NULL COMMENT 'FTP프로토콜코드아이디',
  `CON_ID` varchar(30) DEFAULT NULL COMMENT '접속ID',
  `CON_PW` varchar(100) DEFAULT NULL COMMENT '접속암호',
  `CON_IP` varchar(100) DEFAULT NULL COMMENT '접속IP',
  `CON_PORT` varchar(10) DEFAULT NULL COMMENT '접속PORT',
  `CON_FOLDR_PATH` varchar(200) DEFAULT NULL COMMENT '접속폴더경로',
  `FTP_DESC` varchar(500) DEFAULT NULL COMMENT 'ftp설명',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='COM_EXTR_FTP';


-- com.com_extr_target_level definition

CREATE TABLE `com_extr_target_level` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT '어카운트ID',
  `TARGET_LEVEL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '타겟레벨 유형코드',
  `TARGET_LEVEL_NM` varchar(50) NOT NULL COMMENT '타겟레벨명',
  `DB_NM` varchar(50) DEFAULT NULL COMMENT 'DB명',
  `CON_IP` varchar(200) DEFAULT NULL COMMENT '접속IP',
  `CON_PORT` varchar(50) DEFAULT NULL COMMENT '접속PORT',
  `CON_ID` varchar(50) DEFAULT NULL COMMENT '접속ID',
  `CON_PW` varchar(100) DEFAULT NULL COMMENT '접속암호',
  `CON_DB_TYPE` varchar(32) NOT NULL COMMENT '접속DB 유형',
  `TARGET_DESC` varchar(100) DEFAULT NULL COMMENT '타겟레벨 설명',
  `CON_OPTION` varchar(2000) DEFAULT NULL COMMENT '접속 옵션',
  `AWS_SECRET_NM` varchar(50) DEFAULT NULL COMMENT 'AWS 시크릿 이름',
  `SERVICE_NM` varchar(50) DEFAULT NULL COMMENT '서비스 이름',
  `CON_URL` varchar(500) DEFAULT NULL COMMENT '접속URL',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='외부타겟레벨';


-- com.com_extr_tbl definition

CREATE TABLE `com_extr_tbl` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT 'ACCNT_ID',
  `TARGET_LEVEL_ID` varchar(32) NOT NULL COMMENT '타겟 레벨 ID',
  `TBL_SCHEMA_NM` varchar(20) NOT NULL COMMENT '테이블 스키마 명',
  `TBL_ENG_NM` varchar(50) NOT NULL COMMENT '테이블영문명',
  `TBL_KOR_NM` varchar(50) NOT NULL COMMENT '테이블한글명',
  `TBL_DESC` varchar(100) DEFAULT NULL COMMENT '테이블설명',
  `TBL_HINT` varchar(200) DEFAULT NULL COMMENT '테이블힌트',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='외부테이블';


-- com.com_file definition

CREATE TABLE `com_file` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT '국가',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT '언어',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT '통화',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `FILE_PATH` varchar(200) DEFAULT NULL COMMENT '파일경로',
  `FILE_NAME` varchar(200) DEFAULT NULL COMMENT '파일명',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '파일유형',
  `FILE_SIZE` int DEFAULT NULL COMMENT '파일크기',
  `ORI_FILE_NAME` varchar(200) DEFAULT NULL COMMENT '원본파일명',
  `SEQ` int DEFAULT '0' COMMENT '순서',
  `PARENT_ID` varchar(32) DEFAULT NULL COMMENT '상위아이디',
  `DESCRIPTION` varchar(200) DEFAULT NULL COMMENT '비고',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='COM_FILE';


-- com.com_in_column definition

CREATE TABLE `com_in_column` (
  `NO` varchar(10) NOT NULL COMMENT 'NO',
  `OWNER` varchar(32) NOT NULL COMMENT '소유자',
  `TBL_NAME` varchar(50) NOT NULL COMMENT '테이블명',
  `ENT_NAME` varchar(50) DEFAULT NULL COMMENT '엔티티명',
  `COL_NAME` varchar(50) NOT NULL COMMENT '컬럼명',
  `DATA_TYPE` varchar(50) DEFAULT NULL COMMENT '데이터유형',
  `DATA_LEN` varchar(32) DEFAULT NULL COMMENT '데이터길이',
  `DATA_PRE` varchar(32) DEFAULT NULL COMMENT 'DATA_PRE',
  `DATA_SCA` varchar(32) DEFAULT NULL COMMENT 'DATA_SCA',
  `PKNO` varchar(32) DEFAULT NULL COMMENT 'PK',
  `REQ_GB` varchar(32) DEFAULT NULL COMMENT 'REQ_GB',
  `DEFAULTS` varchar(100) DEFAULT NULL COMMENT '기본값',
  `ATTR_NAME` varchar(50) DEFAULT NULL COMMENT '어트리뷰트명',
  `COMMENTS` varchar(300) DEFAULT NULL COMMENT '코멘트',
  `USE_YN` varchar(1) DEFAULT NULL COMMENT '사용여부',
  `COMM_CODE` varchar(32) DEFAULT NULL COMMENT '공통코드',
  `REG_MOD_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `REG_DT` varchar(32) DEFAULT NULL COMMENT '생성일시',
  `MOD_DT` varchar(32) DEFAULT NULL COMMENT '수정일시',
  PRIMARY KEY (`OWNER`,`TBL_NAME`,`COL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='멀티스테이지조건';


-- com.com_srch_tbl_list definition

CREATE TABLE `com_srch_tbl_list` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT '국가코드',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT '화폐단위',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT NULL COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `ACCNT_ID` varchar(32) DEFAULT NULL COMMENT '어카운트ID',
  `TBL_SCHMA_NM` varchar(50) NOT NULL COMMENT '테이블스키마명',
  `TBL_ENG_NM` varchar(50) NOT NULL COMMENT '테이블영문명',
  `TBL_KOR_NM` varchar(150) DEFAULT NULL COMMENT '테이블한글명',
  `TBL_DESC` varchar(300) DEFAULT NULL COMMENT '테이블설명',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='조회조건 테이블 목록';


-- com.com_webservice definition

CREATE TABLE `com_webservice` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL COMMENT '삭제여부',
  `HOST` varchar(100) DEFAULT NULL COMMENT '호스트',
  `PORT` varchar(10) DEFAULT NULL COMMENT '포트',
  `ACCESS_TOKEN` varchar(50) DEFAULT NULL COMMENT 'OAUTH2 API 발급 토큰',
  `REFRESH_TOKEN` varchar(50) DEFAULT NULL COMMENT 'OAUTH2 API 재 발급 토큰',
  `MALL_ID` varchar(50) DEFAULT NULL COMMENT 'OAUTH2 API 몰 ID',
  `CLIENT_ID` varchar(50) DEFAULT NULL COMMENT 'OAUTH2 API CLIENT ID',
  `CLIENT_SECRET_ID` varchar(50) DEFAULT NULL COMMENT 'OAUTH2 API CLIENT SECRET ID',
  `SITENAME` varchar(100) DEFAULT NULL COMMENT '사이트 이름',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.comm_code definition

CREATE TABLE `comm_code` (
  `ID` varchar(32) NOT NULL COMMENT 'rid',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일자',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일자',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'flag',
  `COUNTRY` char(2) DEFAULT 'KR' COMMENT '국가',
  `LANG` char(2) NOT NULL DEFAULT 'ko' COMMENT '언어',
  `CURRENCY` char(3) DEFAULT 'KRW' COMMENT '환율',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `GROUP_NAME` varchar(100) DEFAULT NULL COMMENT '그룹코드명',
  `GROUP_CODE` varchar(50) DEFAULT NULL COMMENT '그룹코드',
  `MARK_NAME` text COMMENT '코드명',
  `CODE_NAME` varchar(50) DEFAULT NULL COMMENT '코드',
  `SEQ` int DEFAULT '0' COMMENT '순서',
  `MARK_CODE` varchar(100) DEFAULT NULL COMMENT 'MARK_CODE',
  `PAR_CODE_ID` varchar(100) DEFAULT NULL COMMENT '부모코드Rid',
  `ATTRIB01` text COMMENT 'ATTRIB01',
  `ATTRIB02` text COMMENT 'ATTRIB02',
  `ATTRIB03` text COMMENT 'ATTRIB03',
  `ATTRIB04` varchar(1500) DEFAULT NULL COMMENT 'ATTRIB04',
  `ATTRIB05` varchar(1500) DEFAULT NULL COMMENT 'ATTRIB05',
  `API_YN` char(1) DEFAULT NULL COMMENT 'API여부',
  `SB_CD` varchar(100) DEFAULT NULL COMMENT 'SIEBEL LOV',
  PRIMARY KEY (`ID`,`LANG`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='공통코드관리';


-- com.crm_division definition

CREATE TABLE `crm_division` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `RID_PAR_DIV` varchar(32) DEFAULT NULL COMMENT '상위부서RID',
  `RID_LOY_PGM` varchar(32) DEFAULT NULL COMMENT '로열티프로그램RID',
  `RID_LOY_CHNL` varchar(32) DEFAULT NULL COMMENT '로열티채널RID',
  `DIV_SEQ` bigint NOT NULL COMMENT '부서순번',
  `PAR_DIV_SEQ` bigint DEFAULT NULL COMMENT '상위 부서 순번',
  `DIV_NO` varchar(32) DEFAULT NULL COMMENT '부서번호',
  `PAR_DIV_NO` varchar(32) DEFAULT NULL COMMENT '상위부서코드',
  `DIV_NM` varchar(60) DEFAULT NULL COMMENT '부서명',
  `DIV_LVL` varchar(2) DEFAULT NULL COMMENT '부서레벨',
  `DIV_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '부서레빌타입코드',
  `DIV_STATUS` varchar(32) DEFAULT NULL COMMENT '조직상태',
  `RID_LVL1` varchar(32) DEFAULT NULL COMMENT '레벨1부서RID',
  `RID_LVL2` varchar(32) DEFAULT NULL COMMENT '레벨2부서RID',
  `RID_LVL3` varchar(32) DEFAULT NULL COMMENT '레벨3부서RID',
  `RID_LVL4` varchar(32) DEFAULT NULL COMMENT '레벨4부서RID',
  `RID_LVL5` varchar(32) DEFAULT NULL COMMENT '레벨5부서RID',
  `RID_LVL6` varchar(32) DEFAULT NULL COMMENT '레벨6부서RID',
  `RID_LVL7` varchar(32) DEFAULT NULL COMMENT '레벨7부서RID',
  `RID_LVL8` varchar(32) DEFAULT NULL COMMENT '레벨8부서RID',
  `RID_LVL9` varchar(32) DEFAULT NULL COMMENT '레벨9부서RID',
  `RID_LVL10` varchar(32) DEFAULT NULL COMMENT '레벨10부서RID',
  `RID_LVL11` varchar(32) DEFAULT NULL COMMENT '레벨11부서RID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT 'COUNTRY',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CAP_EMP_NO` varchar(50) DEFAULT NULL COMMENT '부서장 사번',
  `B2B_EDPDATETIME` datetime DEFAULT NULL COMMENT 'B2B유입일시',
  `DISPLAY_ORDER` varchar(45) DEFAULT NULL COMMENT 'ENIS 노출순서',
  `DEPTNAMEENG` varchar(100) DEFAULT NULL COMMENT '부서영문명',
  `ISBRANCHYN` varchar(1) DEFAULT NULL COMMENT '지사여부',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.crm_user definition

CREATE TABLE `crm_user` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '활성여부(활성 : 1 / 삭제 : 0)',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT '국가코드(KR: 한국, US: 미국)',
  `CURRENCY` varchar(3) DEFAULT NULL COMMENT '화폐단위(KRW: 원화, USD: 달러)',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트ID',
  `DATA_AUTH_LVL_SEG` varchar(32) DEFAULT NULL,
  `DATA_AUTH_LVL_UI` varchar(32) DEFAULT NULL,
  `DAUTH_MGMT_DIV` varchar(32) DEFAULT NULL,
  `ID_EMPLOYEE` varchar(32) DEFAULT NULL COMMENT '직원 RID',
  `PW_EXPIR_DATE` datetime DEFAULT NULL,
  `RID_LOY_PGM` varchar(32) DEFAULT NULL,
  `RID_PAR_USER` varchar(32) DEFAULT NULL,
  `TEMP_PW_FLG` varchar(1) DEFAULT NULL,
  `USER_ID` varchar(50) DEFAULT NULL,
  `USER_PW` varchar(200) DEFAULT NULL,
  `USER_STAT` varchar(32) DEFAULT 'ACTIVE',
  `USER_PW_CNT` int DEFAULT '0' COMMENT 'USER_PW_CNT',
  `USER_PW_BEF_1` varchar(200) DEFAULT NULL COMMENT 'USER_PW_BEF_1',
  `USER_PW_BEF_2` varchar(200) DEFAULT NULL COMMENT 'USER_PW_BEF_2',
  `FIRST_LOGIN_FLG` int DEFAULT '1' COMMENT '최초로그인여부(1:최초)',
  `USER_PW_LOCK_DATE` datetime DEFAULT NULL COMMENT '로그인 잠금 일시',
  `USER_AUTH_PW_CNT` int DEFAULT NULL COMMENT '이중인증 인증실패횟수',
  `USER_AUTH_PW` varchar(5) DEFAULT NULL COMMENT '이중인증 비밀번호',
  `USER_AUTH_PW_DATE` datetime DEFAULT NULL COMMENT '이중인증 비밀번호 발급 시간',
  `SNS_GOOGLE_KEY` varchar(171) DEFAULT NULL COMMENT '구글인증토큰',
  `SNS_KAKAO_KEY` varchar(100) DEFAULT NULL COMMENT '카카오인증토큰',
  `SNS_NAVER_KEY` varchar(100) DEFAULT NULL COMMENT '네이버인증토큰',
  `SNS_FACEBOOK_KEY` varchar(100) DEFAULT NULL COMMENT '페이스북인증토큰',
  `ACES_START_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '접근시작일',
  `ACES_END_DATE` datetime DEFAULT NULL COMMENT '접근종료일',
  `CTI_USER_ID` varchar(50) DEFAULT NULL COMMENT 'CTI USER ID',
  `CTI_USER_TEL` varchar(50) DEFAULT NULL,
  `USER_SR_SRVY_URL` varchar(200) DEFAULT NULL COMMENT '상담사별상담설문URL',
  `EVNT_CD` varchar(100) DEFAULT NULL COMMENT '이벤트코드, 700/ 701',
  `EVNT_NM` varchar(100) DEFAULT NULL COMMENT '이벤트명, 계정생성/ 계정삭제',
  `EVNT_SVRY` varchar(100) DEFAULT NULL COMMENT '이벤트심각도,상/ 중/ 하',
  `HOST_NM` varchar(100) DEFAULT NULL COMMENT '작업호스트명,사용자 컴퓨터 HostName',
  `IP` varchar(100) DEFAULT NULL COMMENT '사용자 IP',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.crm_user_pwd definition

CREATE TABLE `crm_user_pwd` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT NULL COMMENT '활성여부(활성 : 1 / 삭제 : 0)',
  `RID_CRM_USER` varchar(32) DEFAULT NULL COMMENT 'CRM 사용자 RID',
  `USER_PW` varchar(200) DEFAULT NULL COMMENT '사용자 비밀번호',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.employee definition

CREATE TABLE `employee` (
  `ID` varchar(32) NOT NULL COMMENT 'TBL_PKEY자동채번',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '활성여부(활성 : 1 / 삭제 : 0)',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT '국가코드(KR: 한국, US: 미국)',
  `CURRENCY` varchar(3) DEFAULT NULL COMMENT '화폐단위(KRW: 원화, USD: 달러)',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트ID',
  `ADDRESS1` varchar(100) DEFAULT NULL COMMENT '주소1',
  `ADDRESS2` varchar(100) DEFAULT NULL COMMENT '주소2',
  `ADMIN_USER` varchar(1) DEFAULT NULL COMMENT '관리자여부',
  `AUTHORITY` date DEFAULT NULL COMMENT '권한',
  `BIRTHDAY` varchar(32) DEFAULT NULL COMMENT '생일',
  `DEACTIVE_CODE` varchar(50) DEFAULT NULL COMMENT '비활성화 코드',
  `DEACTIVE_DATE` date DEFAULT NULL COMMENT '비활성화 일자',
  `EMAIL` varchar(200) DEFAULT NULL COMMENT '이메일주소',
  `EMP_NO` varchar(50) DEFAULT NULL COMMENT '사번',
  `EMP_TYPE` varchar(32) DEFAULT NULL COMMENT '직원유형',
  `ENTER_DATE` date DEFAULT NULL COMMENT '입사일',
  `EXTENTION` varchar(4) DEFAULT NULL COMMENT '내선번호',
  `GENDER` varchar(32) DEFAULT NULL COMMENT '성별',
  `MOBILE1` varchar(4) DEFAULT NULL COMMENT '핸드폰1',
  `MOBILE2` varchar(4) DEFAULT NULL COMMENT '핸드폰2',
  `MOBILE3` varchar(4) DEFAULT NULL COMMENT '핸드폰3',
  `NAME` varchar(100) DEFAULT NULL COMMENT '성명',
  `PASSWORD` varchar(50) DEFAULT NULL COMMENT '암호',
  `PHONE1` varchar(4) DEFAULT NULL COMMENT '전화번호1',
  `PHONE2` varchar(4) DEFAULT NULL COMMENT '전화번호2',
  `PHONE3` varchar(4) DEFAULT NULL COMMENT '전화번호3',
  `POSITION` varchar(32) DEFAULT NULL COMMENT '직위',
  `POST_NO` varchar(6) DEFAULT NULL COMMENT '우편번호',
  `RESPONSE_STATUS` varchar(32) DEFAULT NULL COMMENT '응답 상태',
  `RESPONSIBILITY` varchar(32) DEFAULT NULL COMMENT '책임',
  `RID_DIVISION` varchar(32) DEFAULT NULL COMMENT '부서 RID',
  `SERV_STATUS` varchar(32) DEFAULT NULL COMMENT '서비스 상태',
  `TEMP_FLAG` int DEFAULT NULL COMMENT '삭제여부 (활성 : 1 / 삭제 : 0)',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `WORK_STATUS` varchar(32) DEFAULT 'HOLDOFFICE' COMMENT '근무 상태',
  `SVR_REQ_FLG` varchar(1) DEFAULT NULL COMMENT '상담요청 할당여부',
  `EXCEL_FLG` varchar(1) DEFAULT NULL COMMENT '엑셀출력',
  `AGENT_FLG` varchar(1) DEFAULT NULL COMMENT '회원전체조회금지',
  `POINT_APPROVER_FLG` varchar(1) DEFAULT NULL COMMENT '수동적립 포인트 승인',
  `CAMPAIGN_APPROVER_FLG` varchar(1) DEFAULT NULL COMMENT '캠페인,프로모션 승인',
  `MEM_DELETE` varchar(1) DEFAULT NULL COMMENT '회원탈퇴',
  `SMS_SEND_FLG` varchar(1) DEFAULT NULL COMMENT '회원가입 채널 전송',
  `PWD_DECRYPT_FLG` varchar(1) DEFAULT NULL COMMENT '카드비밀번호 복호화',
  `POINT_BULK_FST_FLG` varchar(1) DEFAULT NULL COMMENT '포인트일괄승인1차검수',
  `POINT_BULK_SEC_FLG` varchar(1) DEFAULT NULL COMMENT '포인트일괄승인2차검수',
  `LANG` varchar(3) DEFAULT NULL COMMENT '언어',
  `MOBILE_NO` varchar(200) DEFAULT NULL COMMENT '핸드폰번호',
  `PHONE_NO` varchar(200) DEFAULT NULL COMMENT '전화번호',
  `RETIRE_DATE` date DEFAULT NULL COMMENT '퇴사일',
  `B2B_USER_ID` varchar(8) DEFAULT NULL COMMENT 'B2B 사용자 ID',
  `B2B_EDPDATETIME` date DEFAULT NULL COMMENT '원 데이터 갱신일',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.excel_down_d definition

CREATE TABLE `excel_down_d` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부 (활성 : 1 / 삭제 : 0)',
  `RID_EXCEL_H` varchar(32) DEFAULT NULL COMMENT 'EXCEL_DOWN_H RID',
  `EXCEL_CELL` varchar(3) DEFAULT NULL COMMENT '엑셀 cell 번호(A3,B3,C3..)',
  `DATA_FIELD` varchar(40) DEFAULT NULL COMMENT 'DTO 변수명(컬럼명)',
  `HEAD_NM` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '엑셀 헤더명',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.excel_down_h definition

CREATE TABLE `excel_down_h` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부 (활성 : 1 / 삭제 : 0)',
  `PGM_ID` varchar(32) DEFAULT NULL COMMENT '프로그램 ID',
  `TEMPLETE_FILE` varchar(100) DEFAULT NULL COMMENT '엑셀 템플릿 파일 Path',
  `TITLE` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci DEFAULT NULL COMMENT '엑셀 다운로드 제목',
  `EXCEL_CREATE_TYPE` varchar(1) DEFAULT NULL COMMENT '엑셀 생성 유형(G: 기본, T:템플릿)',
  `EXCEL_SEQ` bigint DEFAULT '1' COMMENT '엑셀 다운로드 순번',
  `OBJCODE` varchar(32) DEFAULT NULL COMMENT '오브젝트 코드',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.excel_upload_h definition

CREATE TABLE `excel_upload_h` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `PGM_ID` varchar(32) DEFAULT NULL COMMENT '프로그램RID',
  `TITLE` varchar(60) DEFAULT NULL COMMENT '제목',
  `OBJ_CODE` varchar(20) DEFAULT NULL COMMENT '오브젝트코드',
  `TEMPLATE_FILE` varchar(100) DEFAULT NULL COMMENT '템플릿파일경로',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- com.image definition

CREATE TABLE `image` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `IMAGE_FOLDER` varchar(200) DEFAULT NULL COMMENT 'IMAGE_FOLDER',
  `IMAGE_FILE_NAME` varchar(50) DEFAULT NULL COMMENT 'IMAGE_FILE_NAME',
  `IMAGE_FILE_TYPE` varchar(10) DEFAULT NULL COMMENT 'IMAGE_FILE_TYPE',
  `IMAGE_FLAG` int DEFAULT '1' COMMENT 'IMAGE_FLAG',
  `SEQ` int DEFAULT '0' COMMENT 'SEQ',
  `IMAGE_TYPE` varchar(32) DEFAULT NULL COMMENT 'IMAGE_TYPE',
  `PARENT_ID` varchar(32) DEFAULT NULL COMMENT '원본이미지파일이름',
  `IMG_SIZE` int DEFAULT NULL COMMENT 'IMG_SIZE',
  `IMG_DESC` varchar(200) DEFAULT NULL COMMENT 'IMG_DESC',
  `ORI_IMG_FILE_NM` varchar(200) DEFAULT NULL COMMENT '원본 이미지 파일명',
  `IMG_LANG` varchar(2) DEFAULT NULL COMMENT '이미지 LANG',
  `IMG_WIDTH` varchar(100) DEFAULT NULL COMMENT '이미지 가로 크기',
  `IMG_HEIGHT` varchar(100) DEFAULT NULL COMMENT '이미지 세로 크기',
  `IMAGE_UMS_FOLDER` varchar(200) DEFAULT NULL COMMENT 'UMS 파일 경로',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='IMAGE';


-- com.kakao_alt_btn definition

CREATE TABLE `kakao_alt_btn` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `RID_CONTS_MST` varchar(32) NOT NULL COMMENT 'RID_CONTS_MST',
  `SEQ_NO` varchar(2) DEFAULT NULL COMMENT '순서',
  `BTN_TYPE_CD` varchar(2) DEFAULT NULL COMMENT '버튼유형(WL:웹링크, AL:앱링크)',
  `BTN_NM` varchar(200) DEFAULT NULL COMMENT '버튼명',
  `WEB_URL` varchar(2000) DEFAULT NULL COMMENT '웹 URL',
  `MOBILE_URL` varchar(2000) DEFAULT NULL COMMENT '모바일URL',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='카카오알림톡버튼';


-- com.`language` definition

CREATE TABLE `language` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `LANG_NAME` varchar(50) DEFAULT NULL COMMENT 'LANG_NAME',
  `LANG_CODE` varchar(50) DEFAULT NULL COMMENT 'LANG_CODE',
  `SEQ` int DEFAULT '0' COMMENT 'SEQ',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LANGUAGE';


-- com.login_history definition

CREATE TABLE `login_history` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `CHANNEL` varchar(32) DEFAULT NULL COMMENT 'CHANNEL',
  `DEVICE` varchar(32) DEFAULT NULL COMMENT 'DEVICE',
  `AREA` varchar(32) DEFAULT NULL COMMENT 'AREA',
  `SERVER` varchar(20) DEFAULT NULL COMMENT 'SERVER',
  `TARGET_ID` varchar(32) NOT NULL COMMENT 'TARGET_ID',
  `IP` varchar(32) DEFAULT NULL COMMENT 'IP',
  `SESSN_ID` varchar(200) DEFAULT NULL COMMENT '세션아이디',
  `LOGIN_SUCCESS_YN` varchar(1) DEFAULT 'Y' COMMENT 'LOGIN_SUCCESS_YN',
  `LOGIN_USER_ID` varchar(50) DEFAULT NULL COMMENT 'LOGIN_USER_ID',
  `EVNT_CD` varchar(100) DEFAULT NULL COMMENT '이벤트코드, (600/ 601/602/603/604)',
  `EVNT_NM` varchar(100) DEFAULT NULL COMMENT '이벤트명, (로그인성공,로그인실패,로그아웃성공,로그아웃실패,계정잠김)',
  `EVNT_SVRY` varchar(100) DEFAULT NULL COMMENT '이벤트심각도,상/ 중/ 하',
  `HOST_NM` varchar(100) DEFAULT NULL COMMENT '작업호스트명,사용자 컴퓨터 HostName',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LOGIN_HISTORY';


-- com.loy_login_auth definition

CREATE TABLE `loy_login_auth` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `AUTH_TYPE` varchar(10) DEFAULT NULL COMMENT 'AUTH_TYPE',
  `LOGIN_ID` varchar(100) DEFAULT NULL COMMENT 'LOGIN_ID',
  `TOKENID` varchar(32) DEFAULT NULL COMMENT 'TOKENID',
  `REQ_DT` datetime DEFAULT NULL COMMENT 'REQ_DT',
  `AUTH_LIMIT_DT` datetime DEFAULT NULL COMMENT 'AUTH_LIMIT_DT',
  `AUTH_DT` datetime DEFAULT NULL COMMENT 'AUTH_DT',
  `AUTH_LOGIN_LIMIT_DT` datetime DEFAULT NULL COMMENT 'AUTH_LOGIN_LIMIT_DT',
  `AUTH_SUCCESS_YN` varchar(1) DEFAULT NULL COMMENT 'AUTH_SUCCESS_YN',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LOY_LOGIN_AUTH';


-- com.menu definition

CREATE TABLE `menu` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `MENU_NM` varchar(100) DEFAULT NULL COMMENT 'MENU_NM',
  `PRNTS_MENU_ID` varchar(32) DEFAULT NULL COMMENT 'PRNTS_MENU_ID',
  `SORT_ODGR` int DEFAULT NULL COMMENT 'SORT_ODGR',
  `MENU_LVL` varchar(10) DEFAULT NULL COMMENT 'MENU_LVL',
  `PRIVACY_FLG` int DEFAULT '0' COMMENT '개인정보 메뉴 여부 (1:개인정보처리 포함 메뉴)',
  `MENU_NM_EN` varchar(100) DEFAULT NULL COMMENT '메뉴명(영문)',
  `ICON_IMG` varchar(100) DEFAULT NULL COMMENT '메뉴아이콘 이미지 경로',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MENU';


-- com.menu_pgm_rel definition

CREATE TABLE `menu_pgm_rel` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` varchar(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `MENU_ID` varchar(32) DEFAULT NULL COMMENT 'MENU_ID',
  `PGM_ID` varchar(32) DEFAULT NULL COMMENT 'PGM_ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MENU_PGM_REL';


-- com.menu_prog definition

CREATE TABLE `menu_prog` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `MENU_ID` varchar(32) NOT NULL COMMENT 'MENU_ID',
  `PROGRAM_ID` varchar(32) NOT NULL COMMENT 'PROGRAM_ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MENU_PROG';


-- com.mkt_chnl definition

CREATE TABLE `mkt_chnl` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CHNL_NM` varchar(30) DEFAULT NULL COMMENT '채널명',
  `CHNL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '채널유형코드',
  `CHNL_STATUS_CD` varchar(32) DEFAULT NULL COMMENT '채널상태코드',
  `PTNR_ACCNT_ID` varchar(32) DEFAULT NULL COMMENT '파트너 업체 정보',
  `COST_UCOST` int DEFAULT '0' COMMENT '비용단가',
  `APLY_START_DD` date DEFAULT NULL COMMENT '적용시작일자',
  `APLY_END_DD` date DEFAULT NULL COMMENT '적용종료일자',
  `CON_DB_TYPE` varchar(32) DEFAULT NULL COMMENT '접속 DB 유형',
  `CON_ID` varchar(30) DEFAULT NULL COMMENT '접속ID',
  `CON_PW` varchar(60) DEFAULT NULL COMMENT '접속암호',
  `CON_IP` varchar(100) DEFAULT NULL COMMENT '접속IP',
  `CON_PORT` varchar(10) DEFAULT NULL COMMENT '접속PORT',
  `CON_URL` varchar(200) DEFAULT NULL COMMENT '접속 웹페이지/API',
  `CHNL_DESC` varchar(200) DEFAULT NULL COMMENT '채널설명',
  `SENDABLE_START_TIME` varchar(6) DEFAULT NULL COMMENT '발송가능 시작시간',
  `SENDABLE_END_TIME` varchar(6) DEFAULT NULL COMMENT '발송가능 종료시간',
  `CHNL_GUIDE` varchar(2000) DEFAULT NULL COMMENT '채널가이드',
  `AWS_SECRET_NM` varchar(50) DEFAULT NULL COMMENT '서비스명',
  `SERVICE_NM` varchar(50) DEFAULT NULL COMMENT '서비스명',
  `CON_API_TYPE` varchar(32) DEFAULT NULL COMMENT 'CON_API_TYPE',
  `API_KEY` varchar(60) DEFAULT NULL COMMENT 'API_KEY',
  `API_SECRET_KEY` varchar(60) DEFAULT NULL COMMENT 'API_SECRET_KEY',
  `CON_TYPE` varchar(32) DEFAULT NULL COMMENT 'CON_TYPE',
  `CALL_TYPE_DB` varchar(32) DEFAULT NULL COMMENT 'CALL_TYPE_DB',
  `CNTNT_TYPE` varchar(32) DEFAULT NULL COMMENT 'CNTNT_TYPE',
  `CHAR_SET` varchar(32) DEFAULT NULL COMMENT 'CHAR_SET',
  `CALL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'CALL_TYPE_CD',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='마케팅 채널';


-- com.mkt_chnl_capa definition

CREATE TABLE `mkt_chnl_capa` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `MKT_CHNL_ID` varchar(32) NOT NULL COMMENT '마케팅 채널 ID',
  `SEQ` int DEFAULT NULL COMMENT '순번',
  `PERIOD_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '기간구분코드',
  `MAX_VOL` int DEFAULT NULL COMMENT '최대용량',
  `RSRV_VOL` int DEFAULT NULL COMMENT '예약용량',
  `CHNL_DTL_DESC` varchar(200) DEFAULT NULL COMMENT '채널상세설명',
  `IMG_RESOL_H` varchar(5) DEFAULT NULL COMMENT '이미지 사이즈 최대 높이',
  `IMG_RESOL_W` varchar(32) DEFAULT NULL COMMENT '이미지 사이즈 최대 넓이',
  `UPLD_ETSION_CD` varchar(32) DEFAULT NULL COMMENT '업로드 유형코드',
  `UPLD_TYPE` varchar(10) DEFAULT NULL COMMENT '업로드 파일 유형',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='마케팅 채널별 용량';


-- com.mkt_conts_chnl_rel definition

CREATE TABLE `mkt_conts_chnl_rel` (
  `ID` varchar(32) DEFAULT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CAM_ID` varchar(32) DEFAULT NULL COMMENT '캠페인 ID',
  `CONTENTS_ID` varchar(300) DEFAULT NULL COMMENT '콘텐츠 ID',
  `MKT_CHNL_ID` varchar(32) DEFAULT NULL COMMENT '마케팅 채널 ID',
  `URL_INFO` varchar(300) DEFAULT NULL COMMENT 'URL 정보',
  `ATCM_DESC` varchar(32) DEFAULT NULL COMMENT '부가 설명',
  `TRT_DESC` varchar(300) DEFAULT NULL COMMENT '처리 설명',
  `EXE_DT` varchar(8) DEFAULT NULL COMMENT '실행 일자',
  `EXE_TM` varchar(6) DEFAULT NULL COMMENT '실행 시간',
  `MANY_SEND_YN` varchar(1) DEFAULT NULL COMMENT '다중 전송 여부',
  `UNSENDABLE_TIME_POLICY` varchar(32) DEFAULT NULL COMMENT '전송 불가 시간 정책',
  `WAIT_ID` varchar(32) DEFAULT NULL COMMENT '대기 ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='마케팅 콘텐츠 채널 관계';


-- com.mkt_conts_dtl definition

CREATE TABLE `mkt_conts_dtl` (
  `ID` varchar(32) DEFAULT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT NULL COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CONTS_ID` varchar(32) DEFAULT NULL COMMENT '콘텐츠 ID',
  `CONTS_SUB_TYPE_CD` varchar(3) DEFAULT NULL COMMENT '콘텐츠 하위 유형 코드',
  `SEQ` int DEFAULT NULL COMMENT '순번',
  `CONTS_TYPE_VAL_CD` varchar(20) DEFAULT NULL COMMENT '콘텐츠 유형 값 코드',
  `CONTS_TYPE_VAL` varchar(200) DEFAULT NULL COMMENT '콘텐츠 유형 값',
  `CONTS_TYPE_DESC` varchar(1000) DEFAULT NULL COMMENT '콘텐츠 유형 설명'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='마케팅 콘텐츠 상세';


-- com.mkt_conts_mst definition

CREATE TABLE `mkt_conts_mst` (
  `ID` varchar(32) NOT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CONTS_NO` varchar(20) NOT NULL COMMENT '컨텐츠번호',
  `CONTS_TYPE_CD` varchar(100) DEFAULT NULL COMMENT '컨텐츠유형',
  `CONTS_NM` varchar(200) DEFAULT NULL COMMENT '콘텐츠명',
  `EXE_CHNL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '실행채널유형',
  `CONTS_DIV_CD` varchar(1) DEFAULT NULL COMMENT '콘텐츠구분코드',
  `CONTS_TITLE` varchar(200) DEFAULT NULL COMMENT '콘텐츠제목',
  `CONTS_SUB_TITLE` varchar(200) DEFAULT NULL COMMENT '콘텐츠 제목 상세',
  `CONTS_PRPS_CD` varchar(32) DEFAULT NULL COMMENT '콘텐츠목적코드',
  `CONTS_SBST` varchar(400) DEFAULT NULL COMMENT '콘텐츠내용',
  `CONTS_BOTTOM` varchar(100) DEFAULT NULL COMMENT '하단 메시지',
  `CONTS_HTML_C` varchar(400) DEFAULT NULL COMMENT '콘텐츠HTML',
  `CONTS_DESC` varchar(200) DEFAULT NULL COMMENT '콘텐츠설명',
  `CONTS_VOL` int DEFAULT NULL COMMENT '콘텐츠 용량',
  `IMG_SIZE` int DEFAULT NULL COMMENT '이미지크기',
  `SUB_IMG_SIZE` int DEFAULT NULL COMMENT 'SUB이미지크기',
  `IMG_APLY_CNT` int DEFAULT NULL COMMENT '이미지 적용 건수',
  `IMG_ID` varchar(32) DEFAULT NULL COMMENT '이미지 ID',
  `SUB_IMG_ID` varchar(32) DEFAULT NULL COMMENT 'SUB이미지ID',
  `BCODE_IMG_ID` varchar(32) DEFAULT NULL COMMENT '바코드 이미지 ID',
  `MERGE_IMG_ID` varchar(32) DEFAULT NULL COMMENT 'MERGE_IMG_ID',
  `IMG_LINK_URL` varchar(100) DEFAULT NULL COMMENT '이미지링크URL',
  `EXTRL_IMG_URL` varchar(100) DEFAULT NULL COMMENT '외부저장이미지URL',
  `CONTS_EMAIL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '콘텐츠이메일유형코드',
  `CONTS_PUSH_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'PUSH 유형 코드',
  `CONTS_PUSH_SUB_TYPE_CD` varchar(100) DEFAULT NULL COMMENT 'PUSH SUB 유형 코드',
  `CONTS_PUSH_SUB_TYPE_VAL` varchar(200) DEFAULT NULL COMMENT 'CONTS_PUSH_SUB_TYPE_VAL',
  `CONTS_PUSH_APP_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'PUSH 앱 유형 코드',
  `CONTS_PUSH_SEND_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'PUSH 발송 유형 코드',
  `CONTS_PUSH_PARAM` varchar(2000) DEFAULT NULL COMMENT 'PUSH 파라메터',
  `DEVICE_TYPE_CD` varchar(100) DEFAULT NULL COMMENT '디바이스 유형 코드',
  `SNS_INFO` varchar(32) DEFAULT NULL COMMENT 'SNS 정보',
  `POST_ID` varchar(50) DEFAULT NULL COMMENT '포스팅아이디',
  `RESERVE_POST` varchar(16) DEFAULT NULL COMMENT '게시물예약시간',
  `OPEN_RANGE` varchar(32) DEFAULT NULL COMMENT '공개범위',
  `ATT_TYPE` varchar(32) DEFAULT NULL COMMENT '소셜첨부파일유형',
  `DP_START_DT` date DEFAULT NULL COMMENT '표시시작일시',
  `DP_END_DT` date DEFAULT NULL COMMENT '표시종료일시',
  `CONTS_SEQ` int DEFAULT NULL COMMENT '콘텐츠 순서',
  `CONTS_LOAD_SEQ` int DEFAULT NULL COMMENT '콘텐츠 부하순서',
  `CONTS_ATTEN_MTR` varchar(1000) DEFAULT NULL COMMENT '콘텐츠 주의사항',
  `INQR_NO` varchar(1000) DEFAULT NULL COMMENT '문의번호',
  `NEW_DP_CLO_DT` date DEFAULT NULL COMMENT 'NEW표시마감일시',
  `EV_NO` varchar(20) DEFAULT NULL COMMENT '이벤트번호',
  `HPAGE` varchar(200) DEFAULT NULL COMMENT '홈페이지',
  `APCT_POSBL_NUM` int DEFAULT NULL COMMENT '응모가능수',
  `PSTNG_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '게시유형코드',
  `ATTRIB01` varchar(200) DEFAULT NULL COMMENT '여분필드1',
  `ATTRIB02` varchar(200) DEFAULT NULL COMMENT '여분필드2',
  `ATTRIB03` varchar(200) DEFAULT NULL COMMENT '여분필드3',
  `ATTRIB04` varchar(200) DEFAULT NULL COMMENT '여분필드4',
  `ATTRIB05` varchar(200) DEFAULT NULL COMMENT '여분필드5',
  `ATTRIB06` varchar(200) DEFAULT NULL COMMENT '여분필드6',
  `ATTRIB07` varchar(200) DEFAULT NULL COMMENT '여분필드7',
  `ATTRIB08` varchar(200) DEFAULT NULL COMMENT '여분필드8',
  `ATTRIB09` varchar(200) DEFAULT NULL COMMENT '여분필드9',
  `ATTRIB10` varchar(200) DEFAULT NULL COMMENT '여분필드10',
  `CONTS_HTML` text COMMENT '컨텐츠html',
  `CONTS_HTML_CON` text COMMENT '컨텐츠htmlCon',
  `SEND_CONTS_TITLE` varchar(200) DEFAULT NULL COMMENT '전송컨텐츠제목',
  `SEND_CONTS_SBST` text COMMENT '전송컨텐츠내용',
  `RID_OFR` varchar(32) DEFAULT NULL COMMENT '오퍼RID',
  `TO_CALLBACK_NO` varchar(20) DEFAULT NULL COMMENT '송신자번호',
  `COM_OFR_TYPE` varchar(10) DEFAULT NULL COMMENT '공통오퍼타입(사용X)',
  `SEND_CONTS_ALTER` text COMMENT '전송컨텐츠대체메세지',
  `TEMPL_YN` varchar(2) DEFAULT NULL COMMENT '템플릿 여부',
  `SEND_CONTS_KAKAO_BTN` varchar(200) DEFAULT NULL COMMENT '전송컨텐츠 카카오톡 버튼 리스트',
  `RID_TRANS_SEND_TYPE_1` varchar(32) DEFAULT NULL COMMENT '전환 전송 타입 1 CHILD RID',
  `RID_TRANS_SEND_TYPE_2` varchar(32) DEFAULT NULL COMMENT '전환 전송 타입 2 CHILD RID',
  `SEND_PUSH_URL` varchar(500) DEFAULT NULL COMMENT '전송PUSH URL',
  `CONT_CODE_NO` varchar(100) DEFAULT NULL COMMENT '전송자 코드 번호'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='컨텐츠 마스터';


-- com.mkt_conts_prsnl definition

CREATE TABLE `mkt_conts_prsnl` (
  `ID` varchar(32) DEFAULT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT NULL COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CONTS_ID` varchar(32) DEFAULT NULL COMMENT '컨텐츠 ID',
  `TARGET_ID` varchar(32) DEFAULT NULL COMMENT '타겟 ID',
  `PRSNL_CD` varchar(50) DEFAULT NULL COMMENT '개인화 코드',
  `PRSNL_VAL` varchar(200) DEFAULT NULL COMMENT '개인화 값',
  `PRSNL_VAL1` varchar(200) DEFAULT NULL COMMENT '개인화 값1',
  `PRSNL_VAL2` varchar(200) DEFAULT NULL COMMENT '개인화 값2',
  `PRSNL_VAL3` varchar(200) DEFAULT NULL COMMENT '개인화 값3',
  `PRSNL_VAL4` varchar(200) DEFAULT NULL COMMENT '개인화 값4',
  `PRSNL_VAL5` varchar(200) DEFAULT NULL COMMENT '개인화 값5',
  `PRSNL_VAL6` varchar(200) DEFAULT NULL COMMENT '개인화 값6',
  `PRSNL_VAL7` varchar(200) DEFAULT NULL COMMENT '개인화 값7',
  `PRSNL_VAL8` varchar(200) DEFAULT NULL COMMENT '개인화 값8',
  `PRSNL_VAL9` varchar(200) DEFAULT NULL COMMENT '개인화 값9',
  `PRSNL_VAL10` varchar(200) DEFAULT NULL COMMENT '개인화 값10'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='개인화 컨텐츠';


-- com.mkt_conts_type_chnl_rel definition

CREATE TABLE `mkt_conts_type_chnl_rel` (
  `ID` varchar(32) DEFAULT NULL COMMENT '아이디',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT NULL COMMENT '삭제여부',
  `TYPE` varchar(32) DEFAULT NULL COMMENT '유형',
  `CONTENTS_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '콘텐츠 유형 코드',
  `MKT_EXE_CHNL_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '마케팅 실행 채널 유형 코드'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='마케팅 콘텐츠 유형 채널 관계';


-- com.mobile_version definition

CREATE TABLE `mobile_version` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `TYPE` varchar(12) DEFAULT NULL COMMENT '모바일 구분(MOBILE_TYPE)',
  `STORE_TYPE` varchar(19) DEFAULT NULL COMMENT '앱스토어 구분(STORE_TYPE)',
  `DEPLOY` varchar(15) DEFAULT '0' COMMENT '배포버전',
  `MIN` varchar(15) DEFAULT '0' COMMENT '최소버전',
  `URL` varchar(200) DEFAULT NULL COMMENT 'URL',
  `EXCUTEURL` varchar(200) DEFAULT NULL COMMENT 'EXCUTEURL',
  `DEVICETYPE` varchar(30) DEFAULT NULL COMMENT 'DEVICETYPE',
  `APPID` varchar(200) DEFAULT NULL COMMENT 'APPID',
  `ISDEPLOYING` varchar(1) DEFAULT '0' COMMENT 'ISDEPLOYING',
  `BEACON_SERVER_URL` varchar(100) DEFAULT NULL COMMENT 'BEACON_SERVER_URL',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT 'ACCNT_ID',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `MOD_NUM` int DEFAULT '0' COMMENT 'MOD_NUM',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `DESCRIPTION` varchar(3000) DEFAULT NULL COMMENT '버전 설명',
  `MOBILE_NAME` varchar(100) DEFAULT NULL COMMENT '모바일명',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='모바일 버전 관리';


-- com.`object` definition

CREATE TABLE `object` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` varchar(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `OBJ_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'OBJ_TYPE_CD',
  `OBJ_CD` varchar(40) DEFAULT NULL COMMENT 'OBJ_CD',
  `OBJ_NM` varchar(100) DEFAULT NULL COMMENT 'OBJ_NM',
  `OBJ_DESC` varchar(1500) DEFAULT NULL COMMENT 'OBJ_DESC',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `OBJECT_UN` (`OBJ_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='OBJECT';


-- com.program definition

CREATE TABLE `program` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `PGM_NO` varchar(50) DEFAULT NULL COMMENT '프로그램번호',
  `PGM_NM` varchar(100) DEFAULT NULL COMMENT '프로그램명',
  `PGM_TYPE_CD` varchar(32) DEFAULT NULL COMMENT '프로그램유형코드',
  `PGM_PATH` varchar(250) DEFAULT NULL COMMENT '프로그램 경로(jsp)',
  `MAIN_PGM_ID` varchar(32) DEFAULT NULL COMMENT '메인프로그램 ID',
  `PAR_PGM_ID` varchar(32) DEFAULT NULL COMMENT '상위프로그램ID',
  `MENU_CHK_YN` varchar(1) DEFAULT NULL COMMENT '메뉴등록가능프로그램',
  `TAB_LABEL` varchar(42) DEFAULT NULL COMMENT '탭 라벨명',
  `TAB_SEQ` varchar(10) DEFAULT NULL COMMENT '탭 순서',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PROGRAM';


-- com.push definition

CREATE TABLE `push` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int NOT NULL DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT 'COUNTRY',
  `LANG` varchar(2) NOT NULL DEFAULT 'ko' COMMENT 'LANG',
  `CURRENCY` varchar(3) DEFAULT 'KRW' COMMENT 'CURRENCY',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `REG_ID` varchar(200) DEFAULT NULL COMMENT 'REG_ID',
  `UUID` varchar(36) DEFAULT NULL COMMENT 'UUID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='PUSH';


-- com.screen_msg definition

CREATE TABLE `screen_msg` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '활성여부(1:활성, 0:삭제)',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT '국가코드',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP서비스 ID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트id',
  `LANG_TYPE_CD` varchar(2) DEFAULT NULL COMMENT '언어타입코드',
  `LANG_DESC` varchar(50) DEFAULT NULL COMMENT '언어설명',
  PRIMARY KEY (`RID`),
  UNIQUE KEY `SCREEN_MSG_UN` (`LANG_TYPE_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='화면 메시지';


-- com.screen_msg_attr definition

CREATE TABLE `screen_msg_attr` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '활성여부(1:활성, 0:삭제)',
  `COUNTRY` varchar(2) DEFAULT 'KR' COMMENT '국가코드',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP서비스 ID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트id',
  `RID_LANG` varchar(32) DEFAULT NULL COMMENT '화면언어RID',
  `CTG` varchar(3) DEFAULT NULL COMMENT 'LOY : loyalty, MKT : marketing, COM: 공통, ETC: 기타, ANL : 분석',
  `ATTR` varchar(10) DEFAULT NULL COMMENT '속성',
  `ATTR_VAL` varchar(300) DEFAULT NULL COMMENT '속성값',
  `CREATE_USER` varchar(20) DEFAULT NULL COMMENT '신규생성개발자명',
  `MODIFY_USER` varchar(20) DEFAULT NULL COMMENT '수정개발자명',
  PRIMARY KEY (`RID`),
  UNIQUE KEY `SCREEN_MSG_ATTR_UN` (`RID_LANG`,`ATTR`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='화면메시지속성';


-- com.sys_alert definition

CREATE TABLE `sys_alert` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `ALERT_TYPE_CD` varchar(2) DEFAULT NULL COMMENT '알림유형코드',
  `TITLE` varchar(100) DEFAULT NULL COMMENT '제목',
  `EMAIL_SND_YN` varchar(1) DEFAULT NULL COMMENT '이메일발송여부',
  `SMS_SND_YN` varchar(1) DEFAULT NULL COMMENT 'SMS발송여부',
  `EMAIL_SND_STAT_CD` varchar(7) DEFAULT NULL COMMENT '이메일발송상태코드',
  `SMS_SND_STAT_CD` varchar(6) DEFAULT NULL COMMENT 'SMS발송상태코드',
  `SRC_SYSTEM` varchar(20) DEFAULT NULL COMMENT '발생시스템',
  `CONTENTS` text COMMENT '내역',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='시스템 알림 발송';


-- com.system_mgt definition

CREATE TABLE `system_mgt` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `SYSTEM_NM` varchar(40) DEFAULT NULL COMMENT '시스템명',
  `SYSTEM_TYPE_CD` varchar(6) DEFAULT NULL COMMENT '시스템유형',
  `HOST_NM` varchar(100) DEFAULT NULL COMMENT '호스트명',
  `PORT` varchar(6) DEFAULT NULL COMMENT '포트',
  `PURPOSE_CD` varchar(4) DEFAULT NULL COMMENT '사이트용도',
  `STAT_CD` varchar(1) DEFAULT NULL COMMENT '상태',
  `COMPANY` varchar(40) DEFAULT NULL COMMENT '회사명',
  `SYSTEM_DESC` varchar(100) DEFAULT NULL COMMENT '설명',
  `API_SITE_ID` varchar(40) DEFAULT NULL COMMENT 'API site id',
  `API_SECREET_KEY` varchar(60) DEFAULT NULL COMMENT 'API secreet key',
  `INT_EXT_TYPE_CD` varchar(5) DEFAULT 'INT' COMMENT '대내외 구분 (대내:INT/대외:EXT)',
  `HMAC_USE_YN` varchar(1) DEFAULT 'N' COMMENT 'HMAC 사용 여부',
  `LOG_REG_YN` varchar(1) DEFAULT 'Y' COMMENT '로그 기록 여부',
  `REQ_PAYLOAD_CNVR_YN` varchar(1) DEFAULT 'N' COMMENT '요청 전문 내부 변경 처리 여부',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='시스템관리';


-- com.ui_object definition

CREATE TABLE `ui_object` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT 'CREATE_BY',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT 'MODIFY_BY',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATE_DATE',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'MODIFY_DATE',
  `FLAG` int DEFAULT '1' COMMENT 'FLAG',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT 'COUNTRY',
  `LANG` varchar(2) DEFAULT NULL COMMENT 'LANG',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP_SERVICE_TYPE',
  `TYPE` varchar(32) DEFAULT NULL COMMENT 'TYPE',
  `PGM_ID` varchar(32) DEFAULT NULL COMMENT 'PGM_ID',
  `OBJ_ID` varchar(32) DEFAULT NULL COMMENT 'OBJ_ID',
  `OBJ_TYPE_CD` varchar(32) DEFAULT NULL COMMENT 'OBJ_TYPE_CD',
  `UI_OBJ_NM` varchar(100) DEFAULT NULL COMMENT 'UI_OBJ_NM',
  `UI_OBJ_DESC` varchar(1500) DEFAULT NULL COMMENT 'UI_OBJ_DESC',
  `USE_FLAG` int DEFAULT NULL COMMENT 'USE_FLAG',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='UI_OBJECT';


-- com.user_acl definition

CREATE TABLE `user_acl` (
  `RID` varchar(32) NOT NULL COMMENT 'RID',
  `CREATE_BY` varchar(32) DEFAULT NULL COMMENT '생성자',
  `MODIFY_BY` varchar(32) DEFAULT NULL COMMENT '수정자',
  `CREATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
  `MODIFY_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
  `FLAG` int DEFAULT '1' COMMENT '활성여부(활성 : 1 / 삭제 : 0)',
  `COUNTRY` varchar(2) DEFAULT NULL COMMENT '국가코드(KR: 한국, US: 미국)',
  `CURRENCY` varchar(3) DEFAULT NULL COMMENT '화폐단위(KRW: 원화, USD: 달러)',
  `APP_SERVICE_TYPE` varchar(32) DEFAULT '13e28abc1cf39fdb62b00005' COMMENT 'APP 서비스 ID',
  `ACCNT_ID` varchar(32) DEFAULT '17b571b160f811e5996a0200' COMMENT '어카운트ID',
  `RID_CRM_USER` varchar(32) DEFAULT NULL COMMENT 'RID_CRM_USER',
  `ACL_TYPE` varchar(1) NOT NULL COMMENT 'ACL 유형( 1: ip, 2:IP대역)',
  `ACCESS_IP_ADDR` varchar(50) NOT NULL COMMENT '접근 허용 IP',
  `USE_YN` varchar(1) DEFAULT NULL COMMENT '사용유무(Y: 사용, N: 사용안함)',
  `CREATOR_IP_ADDR` varchar(20) DEFAULT NULL COMMENT '등록자 IP',
  PRIMARY KEY (`RID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='사용자별 접속허용 관리';